### ISSUE TITLE
Search seems to match everything

### ISSUE THREAD

**Issue by atomicptr** [lunaryorn/gnome-search-providers-jetbrains#7]
When I try to search it seems to match every project I have if it can match one see

![image](https://user-images.githubusercontent.com/674705/114366395-b4b55f00-9b7b-11eb-8823-2cbc85db29c0.png)

I think possibly the fuzzy search is a bit too fuzzy :)

**Comment by lunaryorn** [comment]
@atomicptr I'm sorry, I know you mean well, but this won't do.  Hiding every undesired match doesn't exactly help me understand what's going on :shrug: 

I'll test this more thoroughly at some point but if you'd like to have this fixed fast you need to make a pull request, because I can't work from this ticket alone.

I'm closing this because for me it isn't actionable; please do re-open when you can provide more debugging info.

**Comment by atomicptr** [comment]
I've replaced the screenshot with a better example @lunaryorn

**Comment by lunaryorn** [comment]
Mmmh, I wonder why those match :confused:  I'll check.

That aside, do I understand correctly that the extension still works for you, so you're not yet on Gnome 40?  So fixing this wouldn't be that urgent, would it?  

I'm asking because I seriously consider rewriting this thing in Rust, because I really dislike doing anything non-trivial in Python, and it doesn't really offer any benefit, given that we can easily build binaries on Github actions and need to properly install the search provider anyway :shrug: 

But obviously that'd take time, perhaps the whole week or longer, so this wouldn't get fixed soon'ish.

**Comment by atomicptr** [comment]
> That aside, do I understand correctly that the extension still works for you, so you're not yet on Gnome 40? So fixing this wouldn't be that urgent, would it?

I'm using Fedora so I'll upgrade to Gnome 40 probably later this month. So its not urgent right now and to be honest I much rather stick with Gnome 38 for some more time over not having my project search anymore :).

> I'm asking because I seriously consider rewriting this thing in Rust, because I really dislike doing anything non-trivial in Python, and it doesn't really offer any benefit, given that we can easily build binaries on Github actions and need to properly install the search provider anyway shrug

I kinda hoped this might be something trivial like having the fuzzyness on the search being too high hmhm.

**Comment by lunaryorn** [comment]
> I kinda hoped this might be something trivial like having the fuzzyness on the search being too high hmhm.

I don't doubt it his, but I wouldn't want to touch Python any longer than I have to :innocent: After all, if I'm to program in my free time it ought to be fun :slightly_smiling_face: 

In any case there's just a single method that does the matching, so feel free to start tuning; if you end up with good numbers for the scores and reasonable cutoffs I can just use those for Rust right away.

But at this point it starts becoming non-trivial; a fuzzy search is always too fuzzy for someone, so before I start changing those numbers at a whim once we have working ones I'd like to add a few tests which ensure that i.e. in this example we always end up with the expected matches.

And adding tests is already so much easier in Rust :blush:

**Comment by atomicptr** [comment]
I think the issue is this part https://github.com/lunaryorn/gnome-search-providers-jetbrains/blob/main/jetbrains-search-provider.py#L122

The "extractBests" above returns me the desired result if I search something like "flutter_test" in my example but the second one (which I linked) basically returns everything

```
MATCHES
[('flutter_test_app', 86, 'jetbrains-studio.desktop-/home/christopher/dev/flutter_test_app')]
PATH_MATCHES
[('/home/christopher/dev/flutter_test_app', 49, 'jetbrains-studio.desktop-/home/christopher/dev/flutter_test_app'), 
('/home/christopher/dev/dauntless-builder', 28, 'jetbrains-webstorm.desktop-/home/christopher/dev/dauntless-builder'),
('/home/christopher/pkg/typo3-source', 27, 'jetbrains-phpstorm.desktop-/home/christopher/pkg/typo3-source')
```

**Comment by lunaryorn** [comment]
@atomicptr I'm almost done with my Rust reimplementation; it'll use the same dumb string contains check as the old Gnome extension which should fix this issue.

If you've got some time I invite you to test the "rust" branch in this repo :slightly_smiling_face: 

To update run `sudo make uninstall` in "master", and then `make build; sudo make install` in the "rust" branch.

**Comment by atomicptr** [comment]
It seems to work just fine for me so far :)

**Comment by lunaryorn** [comment]
I've added these examples as unit tests to make sure I don't break those when I consider adding fuzzywuzzy back again.

For now things should work as expected; I made a new tag for v1.1.0 now.  

I'll update my AUR package, but other than that you'll have to build from source currently.
